"""Add Calendar and EventLinks

Revision ID: 5e732858f168
Revises: 
Create Date: 2025-12-13 14:23:56.710114

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5e732858f168'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar',
    sa.Column('google_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('discord_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('google_id', 'discord_id')
    )
    op.create_table('eventlink',
    sa.Column('google_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('discord_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('google_id', 'discord_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eventlink')
    op.drop_table('calendar')
    # ### end Alembic commands ###
