"""Discord IDs to big integers

Revision ID: a6f86b1cef13
Revises: 5e732858f168
Create Date: 2025-12-13 15:33:47.726544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a6f86b1cef13'
down_revision: Union[str, Sequence[str], None] = '5e732858f168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('eventlink', 'discord_id', existing_type=sa.INTEGER(), type_=sqlmodel.BigInteger(), existing_nullable=False)
    op.alter_column('calendar', 'discord_id', existing_type=sa.INTEGER(), type_=sqlmodel.BigInteger(), existing_nullable=False)
    op.alter_column('calendar', 'channel_id', existing_type=sa.INTEGER(), type_=sqlmodel.BigInteger(), existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calendar', 'channel_id', existing_type=sqlmodel.BigInteger(), type_=sa.INTEGER(), existing_nullable=True)
    op.alter_column('calendar', 'discord_id', existing_type=sqlmodel.BigInteger(), type_=sa.INTEGER(), existing_nullable=False)
    op.alter_column('eventlink', 'discord_id', existing_type=sqlmodel.BigInteger(), type_=sa.INTEGER(), existing_nullable=False)
    # ### end Alembic commands ###
